// Generated by Selenium IDE
import org.openqa.selenium.chrome.ChromeOptions;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RedditCatsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "Mac_M1/chromedriver");
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--disable-notifications");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fUNTITLE() {
    // Test name: FUN-TITLE
    // Step # | name | target | value
    // 1 | open | /r/cats/ | 
    driver.get("https://www.reddit.com/r/cats/");
    // 2 | setWindowSize | 2502x1359 | 
    driver.manage().window().setSize(new Dimension(2502, 1359));
    // 3 | assertTitle | Cats | 
    assertThat(driver.getTitle(), is("Cats"));
  }
  @Test
  public void fUNJOINBUTTONEXISTS() {
    // Test name: FUN-JOIN-BUTTON-EXISTS
    // Step # | name | target | value
    // 1 | open | https://www.reddit.com/r/cats/ | 
    driver.get("https://www.reddit.com/r/cats/");
    // 2 | setWindowSize | 2502x1359 | 
    driver.manage().window().setSize(new Dimension(2502, 1359));
    // 3 | assertText | css=.\_1Q_zPN5YtTLQVG72WhRuf3 > .\_1LHxa-yaHJwrPK8kuyv_Y4 | Join
    assertThat(driver.findElement(By.cssSelector(".\\_1Q_zPN5YtTLQVG72WhRuf3 > .\\_1LHxa-yaHJwrPK8kuyv_Y4")).getText(), is("Join"));
  }
  @Test
  public void fUNRULE3() {
    // Test name: FUN-RULE-3
    // Step # | name | target | value
    // 1 | open | https://www.reddit.com/r/cats/ | 
    driver.get("https://www.reddit.com/r/cats/");
    // 2 | setWindowSize | 2502x1359 | 
    driver.manage().window().setSize(new Dimension(2502, 1359));
    // 3 | assertText | css=.\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(3) .tbIApBd2DM_drfZQJjIum | No NSFW, animal abuse, or cruelty
    assertThat(driver.findElement(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(3) .tbIApBd2DM_drfZQJjIum")).getText(), is("No NSFW, animal abuse, or cruelty"));
  }
  @Test
  public void fUNRULES10ITEMS() {
    // Test name: FUN-RULES-11-ITEMS
    // Step # | name | target | value
    // 1 | open | https://www.reddit.com/r/cats/ | 
    driver.get("https://www.reddit.com/r/cats/");
    // 2 | setWindowSize | 2502x1359 | 
    driver.manage().window().setSize(new Dimension(2502, 1359));
    // 3 | assertElementPresent | css=.\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(10) .\_36D5hmBSZbFxkFMkiWg6cY | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(10) .\\_36D5hmBSZbFxkFMkiWg6cY"));
      assert(elements.size() > 0);
    }
    // 4 | assertElementNotPresent | css=.\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(11) .\_36D5hmBSZbFxkFMkiWg6cY | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_8ZLJI1-ZiP7pHJ_yO1L4Z:nth-child(11) .\\_36D5hmBSZbFxkFMkiWg6cY"));
      assert(elements.size() == 0);
    }
  }
  @Test
  public void fUNSEARCHSMELLYCAT() {
    // Test name: FUN-SEARCH-SMELLY-CAT
    // Step # | name | target | value
    // 1 | open | https://www.reddit.com/r/cats/ | 
    driver.get("https://www.reddit.com/r/cats/");
    // 2 | setWindowSize | 2502x1359 | 
    driver.manage().window().setSize(new Dimension(2502, 1359));
    // 3 | click | id=header-search-bar | 
    driver.findElement(By.id("header-search-bar")).click();
    // 4 | type | id=header-search-bar | smelly cat
    driver.findElement(By.id("header-search-bar")).sendKeys("smelly cat");
    // 5 | sendKeys | id=header-search-bar | ${KEY_ENTER}
    driver.findElement(By.id("header-search-bar")).sendKeys(Keys.ENTER);
    // 6 | assertText | css=.\_3j9XjJayuKq7dJ8huVnCuS | smelly cat
    assertThat(driver.findElement(By.cssSelector(".\\_3j9XjJayuKq7dJ8huVnCuS")).getText(), is("smelly cat"));
  }
  @Test
  public void fUNSIGNUPLINK() {
    // Test name: FUN-SIGNUP-LINK
    // Step # | name | target | value
    // 1 | open | https://www.reddit.com/r/cats/ | 
    driver.get("https://www.reddit.com/r/cats/");
    // 2 | setWindowSize | 2502x1359 | 
    driver.manage().window().setSize(new Dimension(2502, 1359));
    // 3 | storeAttribute | linkText=Sign Up@href | attribute
    {
      WebElement element = driver.findElement(By.linkText("Sign Up"));
      String attribute = element.getAttribute("href");
      vars.put("attribute", attribute);
    }
    // 4 | assert | attribute | https://www.reddit.com/register/?dest=https%3A%2F%2Fwww.reddit.com%2Fr%2Fcats%2F
    assertEquals(vars.get("attribute").toString(), "https://www.reddit.com/register/?dest=https%3A%2F%2Fwww.reddit.com%2Fr%2Fcats%2F");
  }
}
